
name: Update-Job

on:
 # schedule: # run at midnight
 #   - cron: "0 0 * * *"
  push:
    branches: [ cloud_provider_update_job_#84 ]

jobs:
  update-testdata:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/update_images/testdata
    steps:
    - uses: actions/checkout@v3
      with:
        # check out all branches
        fetch-depth: 0
    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"
        # If credentials aren't available such as PRs from a fork keep
        # going with the remainder of the job.
      continue-on-error: true
#    - name: 'Az CLI login'
#      uses: azure/login@v1
#      with:
#        client-id: ${{ secrets.AZURE_CLIENT_ID }}
#        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#        #secert: ${{ secrets.AZURE_CLIENT_SECRET }}
    - name: Update cloud provider dumps
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        GOOGLE_APPLICATION_CREDENTIALS: "${{ steps.auth.outputs.credentials_file_path }}"
      run: |
       ./update.sh
    - name: Commit cloud provider dumps
      env:
        BRANCH_NAME: cloud_data_update
      run: |
        git config --global user.name Janine Olear
        git config --global user.email pninak@web.de
        git status
        git add .
        git commit -m "Automated cloud provider update $(date +%F)"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        delete-branch: true
        title: '[Update] cloud provider test data'
        body: |
          Update cloud provider test data
          - (Azure) disabled
          - AWS
          - Google
        labels: |
          automated-testdata-update
        reviewers: miyunari
